version: 0.2
#see: https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html

env:
  variables:
    STAGE: "dev"

phases:
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on $(date)
      - terraform apply -input=false -auto-approve -var ACTUAL_STAGE="$STAGE" -var AWS_PROFILE="$TF_ROLE"
  post_build:
    commands:
      - echo Build completed on $(date)
cache:
  paths:
    - terraform/.terraform
