version: 0.2
#see: https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html

env:
  variables:
    REGION: "eu-central-1"
    PROJECTNAME: "iac-core-demo"
    STATE_BUCKET_NAME: "accountid-terraform-states" # example of a state bucket name
    STAGE: "dev"

phases:
  install:
    commands:
      - echo Entered the install phase...
      - apk add --no-cache git make bash # showcase
  pre_build:
    commands:
      - echo Entered the pre_build phase...
      - SRCDIR="$(pwd)"
      - cd terraform
      # colored output is right now not supported by CodeBuild
      - terraform init -no-color -backend-config="region=$REGION"
        -backend-config="bucket=$STATE_BUCKET_NAME"
        -backend-config="key=$PROJECTNAME/$PROJECTNAME-$STAGE.tfstate"
        # -backend-config="role_arn=$TF_ROLE"
  build:
    commands:
      - echo Entered the build phase...build started on $(date)
      - echo $(pwd)
      - ls -la
      # colored output is right now not supported by CodeBuild
      - terraform plan -no-color -var ACTUAL_STAGE="$STAGE" -var AWS_REGION="$REGION" #-var AWS_PROFILE="$TF_ROLE"
  post_build:
    commands:
      - echo Build completed on $(date)
artifacts:
  type: zip
  files:
    # - "terraform/.terraform/**/*"
    - "./**/*"
  name: "sources-and-tf-folder"
# cache:
#   paths:
#     - "terraform/.terraform/**/*"
