version: 0.2
#see: https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html

env:
  variables:
    REGION: "eu-central-1"
    PROJECTNAME: "iac-core-demo"
    STATE_BUCKET_NAME: "accountid-terraform-states" # example of a state bucket name
    STAGE: "dev"

phases:
  install:
    commands:
      - echo Entered the install phase...
      - apk add --no-cache git make bash # showcase
  pre_build:
    commands:
      - echo Entered the pre_build phase...
      - cd terraform
      - terraform init -backend-config="region=$REGION"
        -backend-config="bucket=$STATE_BUCKET_NAME"
        -backend-config="key=$PROJECTNAME/$PROJECTNAME.tfstate"
        -backend-config="role_arn=$TF_ROLE"
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on $(date)
      - terraform plan -var ACTUAL_STAGE="$STAGE" -var AWS_PROFILE="$TF_ROLE"
  post_build:
    commands:
      - echo Build completed on $(date)
cache:
  paths:
    - terraform/.terraform
